Update requirements.txt
`phate` cannot be loaded with the latest version of scikit-learn, since it makes use of the `graph_shortest_path` function:
```
ImportError: cannot import name 'graph_shortest_path' from 'sklearn.utils.graph'
```
This function is deprecated in `scikit-learn 1.2.0` and `scipy.sparse.csgraph.shortest_path` is suggested instead.
Either `phate` uses an older scikit-learn version or it is forced to use the suggested function.